In [1]:
import math
import numpy as np

## Item Similarity

In [2]:
matrix = np.array(
    [
        [0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0], 
        [0, 0, 0, 1, 1, 0, 0, 0], 
        [0, 0, 0, 0, 0, 1, 1, 1], 
        [0, 0, 1, 1, 0, 0, 0, 0], 
        [0, 1, 0, 1, 1, 0, 0, 0]
    ]
)

In [3]:
print("Items : ", matrix.shape[0])
print("Genres : ", matrix.shape[1])

Items :  11
Genres :  8


In [4]:
totalItems = matrix.shape[0]
totalGenres = matrix.shape[1]

weights = np.zeros(matrix.shape)
weights

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
for i in range(0, totalGenres):
    col = matrix[:, i]
    # document frequency
    df = col.sum()
    idf = math.log10(totalItems/df)
    for j in range(0, totalItems):
        weights[j, i] = matrix[j, i] * idf

weights

array([[0.        , 0.43933269, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.74036269, 0.        , 0.74036269, 0.        , 0.        ,
        0.        , 0.        , 0.74036269],
       [0.        , 0.43933269, 0.        , 0.        , 0.43933269,
        0.        , 0.        , 0.        ],
       [0.74036269, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.34242268, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.34242268, 0.43933269,
        0.        , 0.        , 0.        ],
       [0.        , 0.43933269, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.34242268, 0.43933269,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.04139269, 1.041392

## L2 Norm

In [6]:
def norm2(arr):
    sum = 0.0 
    for i in range(0, len(arr)):
        sum += arr[i] * arr[i]
    return math.sqrt(sum)

In [7]:
print(weights[0], "=>", norm2(weights[0]))

[0.         0.43933269 0.         0.         0.         0.
 0.         0.        ] => 0.43933269383026263


## Inner Product

In [8]:
def dot(arr1, arr2):
    sum = 0.0 
    for i in range(0, len(arr1)):
        sum += arr1[i] * arr2[i]
    return sum 

In [9]:
print(dot(weights[0], weights[1]))
print(dot(weights[0], weights[2]))
print(dot(weights[0], weights[3]))

0.0
0.19301321586815529
0.0


## Cosine Similarity

In [10]:
def cosine(arr1, arr2):
    return dot(arr1, arr2) / (norm2(arr1) * norm2(arr2))

In [12]:
print(cosine(weights[0], weights[1]))
print(cosine(weights[0], weights[2]))
print(cosine(weights[0], weights[3]))

0.0
0.7071067811865475
0.0


In [13]:
from numpy import linalg as LA

In [14]:
norms = LA.norm(weights, ord=2, axis=1)

In [15]:
norms

array([0.43933269, 1.28234579, 0.62131025, 0.74036269, 0.34242268,
       0.55701572, 0.43933269, 0.55701572, 1.64837325, 0.81571454,
       0.70942211])

In [17]:
dots = np.matmul(weights, weights.T)
dots

array([[0.19301322, 0.        , 0.19301322, 0.        , 0.        ,
        0.        , 0.19301322, 0.        , 0.        , 0.        ,
        0.19301322],
       [0.        , 1.64441074, 0.        , 0.54813691, 0.        ,
        0.        , 0.        , 0.        , 0.54813691, 0.54813691,
        0.        ],
       [0.19301322, 0.        , 0.38602643, 0.        , 0.        ,
        0.19301322, 0.19301322, 0.19301322, 0.        , 0.        ,
        0.38602643],
       [0.        , 0.54813691, 0.        , 0.54813691, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.11725329,
        0.11725329, 0.        , 0.11725329, 0.        , 0.11725329,
        0.11725329],
       [0.        , 0.        , 0.19301322, 0.        , 0.11725329,
        0.31026651, 0.        , 0.31026651, 0.        , 0.11725329,
        0.31026651],
       [0.19301322, 0.        , 0.19301322, 0.        , 0.

In [18]:
sims = np.divide(np.divide(dots, norms).T, norms)
sims

array([[1.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.6192825 ],
       [0.        , 1.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        , 0.25931542, 0.52401738,
        0.        ],
       [0.70710678, 0.        , 1.        , 0.        , 0.        ,
        0.5577134 , 0.70710678, 0.5577134 , 0.        , 0.        ,
        0.87579771],
       [0.        , 0.57735027, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.6147451 , 0.        , 0.6147451 , 0.        , 0.41978249,
        0.48267834],
       [0.        , 0.        , 0.5577134 , 0.        , 0.6147451 ,
        1.        , 0.        , 1.        , 0.        , 0.25805923,
        0.78516825],
       [1.        , 0.        , 0.70710678, 0.        , 0.